development: 
  cloud_name: "dqwalkact"
  api_key: "595324268824583"
  api_secret: "c9bQ1jeJCKWY2eJc-OFxCKdZIJw"
  secure: true

production:
  cloud_name: "dqwalkact"
  api_key: "595324268824583"
  api_secret: "c9bQ1jeJCKWY2eJc-OFxCKdZIJw"
  secure: true
